### ISSUE TITLE
M1: Rationale for Waterfall Methodology

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#30]
Goal: Rationale for Waterfall Methodology
Success criteria: Determine rationale for choice in Methodology
Start Date: 19 September 2023
End Date: 19 September 2023
Owner: Soon Leung Isaac
Status: Completed

**Comment by tjl081** [comment]
1. Detail: Rationale for Waterfall Methodology
2. Committed to repo: No
3. How does it affect success criteria: Decide the SDLC for the team now to dictate project management style in the future
4. Start Date: 19/09/23
5. End Date: 19/09/23


**Waterfall Decided due to unique project situation, as we will no longer meet the client.
